<div class="row g-2">

  <div class="col-sm-8">

    <div class="border bg-body-tertiary rounded p-2">
      <div class="shadow-sm border bg-body rounded my-2 p-2">
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center gap-2">
            <img src="<? echo $this->user->avatarUrl; ?>" class="rounded-circle" style="width:24px; height:24px;">
            <div class="fw-bold fs-12px">
              <? echo $this->user->login; ?>
            </div>
          </div>
          <div class="fs-10px text-secondary">
            Сегодня в 8:00
          </div>
        </div>
        <div class="d-flex justify-content-between align-items-center">
          <div class="fs-5 fw-bold my-2">
            Обновление 1.0.1
          </div>
          <a class="">Читать...</a>
        </div>
      </div>
      <div class="shadow-sm border bg-body rounded my-2 p-2">
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center gap-2">
            <img src="<? echo $this->user->avatarUrl; ?>" class="rounded-circle" style="width:24px; height:24px;">
            <div class="fw-bold fs-12px">
              <? echo $this->user->login; ?>
            </div>
          </div>
          <div class="fs-10px text-secondary">
            Сегодня в 8:00
          </div>
        </div>
        <div class="d-flex justify-content-between align-items-center">
          <div class="fs-5 fw-bold my-2">
            Обновление 1.0.0
          </div>
          <a class="">Читать...</a>
        </div>
      </div>
    </div>

  </div>

  <div class="col-sm-4">
    <div class="bg-body-tertiary shadow rounded p-2">
      <div>
        Последние проекты
      </div>
    </div>
  </div>
</div>